version: '3.8'

services:
  flask-app:
    image: yck4756/flask-app:latest
    container_name: flask-app-production
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    networks:
      - app-network

networks:
  app-network:
    driver: bridge